'use client'
import { ThemeProvider } from 'next-themes'
import CategoryList from './components/category'
import { NavMenu } from './components/navbar'

import './styles/globals.css'

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang='en'>
      <head>
        <title>Next13 App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='stylesheet' href='//at.alicdn.com/t/c/font_2700222_x3f3dq3pdfo.css' type='text/css' />
        <link rel='icon' href='/favicon.ico' sizes='16*16' />
      </head>
      <body className='overflow-y-scroll dark:bg-dark bg-light'>
        <ThemeProvider attribute='class'>
          <div className='app-container'>
            <NavMenu />
            <main className='flex py-8 max-w-6xl mx-auto relative '>
              <div className='absolute top-0 left-0 right-0'>
                <div className='absolute top-0 overflow-visible opacity-50 dark:opacity-30 left-16'>
                  <div className='mix-blend-multiply absolute w-[700px] h-[900px] rounded-[40rem] circle-obj'></div>
                </div>

                <div className='absolute overflow-visible opacity-50 dark:opacity-30 top-28 left-52'>
                  <div className='mix-blend-multiply absolute w-[600px] h-[600px] rounded-[40rem] circle-obj2'></div>
                </div>
              </div>
              <nav className='w-60 col-start-2 md:block hidden backdrop-blur-sm bg-white/10 rounded-xl p-3'>
                <CategoryList />
              </nav>

              <article className='flex-1 mx-5 rounded-xl border border-zinc-800 p-2 backdrop-blur-sm bg-white/10'>
                {children}
              </article>

              <section className='w-60 md:block hidden backdrop-blur-sm bg-white/10 rounded-xl'>
                <p className='text-white'>右側邊欄</p>
              </section>
            </main>
            <footer className='col-start-3 col-end-4 mt-28 py-8 flex items-center justify-center'>
              <div className='text-sm text-zinc-600'>
                Created by the <b>Next.js</b>
                {' team at '}
                <a href='https://vercel.com'>
                  <b>Vercel</b>
                </a>
                {'. '}
                <a
                  className='underline decoration-dotted underline-offset-4'
                  href='https://github.com/vercel/app-playground'
                >
                  View the code
                </a>
                {' or '}
                <a
                  className='underline decoration-dotted underline-offset-4'
                  href='https://vercel.com/templates/next.js/app-playground'
                >
                  deploy your own
                </a>
                {'.'}
              </div>
            </footer>
          </div>
        </ThemeProvider>
      </body>
    </html>
  )
}
